name: env_anaconda_GenomicBasedClassification_1.2.0
channels:
  - conda-forge
  - nicolasradomski
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _py-xgboost-mutex=2.0
  - adwaita-icon-theme=49.0
  - at-spi2-atk=2.38.0
  - at-spi2-core=2.40.3
  - atk-1.0=2.38.0
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.10.5
  - cairo=1.18.4
  - catboost=1.2.8
  - colorama=0.4.6
  - contourpy=1.3.3
  - cpp-expected=1.1.0
  - cuda-cudart=12.9.79
  - cuda-cudart_linux-64=12.9.79
  - cuda-version=12.9
  - cycler=0.12.1
  - dbus=1.16.2
  - epoxy=1.5.10
  - fmt=11.0.2
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.60.1
  - freetype=2.14.1
  - fribidi=1.0.16
  - gdk-pixbuf=2.44.4
  - glib-tools=2.86.1
  - graphite2=1.3.14
  - graphviz=13.1.2
  - gtk3=3.24.43
  - gts=0.7.6
  - harfbuzz=12.1.0
  - hicolor-icon-theme=0.17
  - icu=75.1
  - imbalanced-learn=0.13.0
  - joblib=1.5.1
  - keyutils=1.6.3
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libarchive=3.7.7
  - libblas=3.9.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.9.0
  - libcups=2.3.3
  - libcurl=8.17.0
  - libdeflate=1.25
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libegl-devel=1.7.0
  - libev=4.33
  - libexpat=2.7.1
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgd=2.3.3
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgl=1.7.0
  - libgl-devel=1.7.0
  - libglib=2.86.1
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libglx-devel=1.7.0
  - libgomp=15.2.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libmamba=2.0.5
  - libnghttp2=1.67.0
  - libnsl=2.0.1
  - libopenblas=0.3.30
  - libpciaccess=0.18
  - libpng=1.6.50
  - librsvg=2.58.4
  - libsolv=0.7.30
  - libsqlite=3.51.0
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtiff=4.7.1
  - libuuid=2.41.2
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxgboost=2.1.3
  - libxkbcommon=1.11.0
  - libxml2=2.13.9
  - libzlib=1.3.1
  - lz4-c=1.10.0
  - lzo=2.10
  - mamba=2.0.5
  - matplotlib-base=3.10.7
  - munkres=1.1.4
  - narwhals=2.10.2
  - ncurses=6.5
  - nlohmann_json=3.11.3
  - numpy=1.26.4
  - openjpeg=2.5.4
  - openssl=3.5.4
  - packaging=25.0
  - pandas=2.2.2
  - pango=1.56.4
  - pcre2=10.46
  - pillow=12.0.0
  - pip=25.2
  - pixman=0.46.4
  - plotly=6.4.0
  - pthread-stubs=0.4
  - py-xgboost=2.1.3
  - pyparsing=3.2.5
  - python=3.12.12
  - python-dateutil=2.9.0.post0
  - python-graphviz=0.21
  - python-tzdata=2025.2
  - python_abi=3.12
  - pytz=2025.2
  - qhull=2020.2
  - readline=8.2
  - reproc=14.2.5.post0
  - reproc-cpp=14.2.5.post0
  - scikit-learn=1.5.2
  - scipy=1.16.3
  - setuptools=80.9.0
  - simdjson=3.12.3
  - six=1.17.0
  - sklearn-compat=0.1.4
  - spdlog=1.15.1
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - tqdm=4.67.1
  - tqdm-joblib=0.0.4
  - tzdata=2025b
  - unicodedata2=17.0.0
  - wayland=1.24.0
  - wheel=0.45.1
  - xgboost=2.1.3
  - xkeyboard-config=2.46
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.2
  - xorg-libxi=1.8.2
  - xorg-libxinerama=1.1.5
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - xorg-xorgproto=2024.1
  - yaml-cpp=0.8.0
  - zlib-ng=2.2.5
  - zstd=1.5.7
prefix: 
  /home/IZSNT/n.radomski/miniconda3/envs/env_anaconda_GenomicBasedClassification_1.2.0
